const P={"6th":399,"7th":399,"8th":399,"9th":99,"10th":99,"11th Arts":149,"11th Science":149,"12th Arts":199,"12th Science":199},F={"6th":399,"7th":399,"8th":399,"9th":499,"10th":599,"11th Arts":699,"11th Science":699,"12th Arts":799,"12th Science":799};
const C=[["Class 6","All Subjects",399,1],["Class 9","Mathematics",99,0],["Class 9","All Subjects",499,0],["Class 10","Mathematics",99,1],["Class 10","All Subjects",599,0],["Class 11 Arts","History",149,0],["Class 11 Arts","All Subjects",699,0],["Class 11 Science","Physics",149,0],["Class 11 Science","All Subjects",699,0],["Class 12 Arts","Hindi",199,0],["Class 12 Arts","All Subjects",799,0],["Class 12 Science","Physics",199,0],["Class 12 Science","All Subjects",799,0]];
const live=[["Class 10 Maths Live","Today • 7 PM","LIVE"],["Class 12 Science Physics","Tomorrow • 6:30 PM","UPCOMING"]];
const rec=[["Real Numbers – Complete Lecture","Class 10 • Maths","48 min"],["Chemical Reactions – Part 1","Class 10 • Science","42 min"],["Hindi Grammar – संज्ञा","Class 10 • Hindi","35 min"]];
let comments=[["Rahul","Sir, next chapter kab hoga?"],["Priya","Bahut achha lecture sir!"]],page="home",sel=null;
function head(){return `<div class=top><div class=brand>THE LEARNING ACADEMY</div><div class=sub>BY AMIT SIR • Class 6th to 12th</div></div>`}
function nav(){return `<div class=nav><button onclick="go('home')">🏠<br>Home</button><button onclick="go('courses')">📚<br>Courses</button><button onclick="go('live')">🔴<br>Live</button><button onclick="go('recorded')">▶️<br>Recorded</button><button onclick="go('profile')">👤<br>Profile</button></div>`}
function shell(x){return head()+`<main class=container>${x}</main>`+nav()}
function course(c,i){return `<div class=card><span class=pill>${c[0]} • ${c[1]}</span><h3>${c[1]} ${c[0]}</h3><div class=price>₹${c[2]}</div><div>${c[3]?"✓ Purchased":"Single/Full course"}</div><button class=btn style="margin-top:10px" onclick="openC(${i})">${c[3]?"Open":"View / Buy"}</button></div>`}
function home(){return shell(`<div class=hero><h1>THE LEARNING ACADEMY</h1><p>Live Classes • Recorded Classes • Notes • Tests • Comments</p><button class="btn gold" onclick="go('courses')">View Courses</button></div><div class=section><h2>🔴 Live Classes</h2></div><div class=grid>${live.map((x,i)=>`<div class="card ${x[2]=='LIVE'?'live':''}"><span class=pill>${x[2]}</span><h3>${x[0]}</h3><p>${x[1]}</p><button class=btn onclick="liveRoom(${i})">${x[2]=='LIVE'?'Join Live':'Set Reminder'}</button></div>`).join("")}</div><div class=section><h2>🎬 Recorded Classes</h2></div><div class=grid>${rec.map((x,i)=>`<div class=card><span class=pill>${x[1]}</span><h3>${x[0]}</h3><p>${x[2]}</p><button class=btn onclick="video(${i})">Watch</button></div>`).join("")}</div><div class=section><h2>Course Prices</h2></div><div class=grid>${Object.keys(P).map(k=>`<div class=card><b>${k}</b><p>Subject: ₹${P[k]}</p><p>Full: ₹${F[k]}</p></div>`).join("")}</div>`)}
function courses(){return shell(`<div class=section><h2>All Courses</h2></div><input class=search placeholder="Search course..." oninput=filter(this.value)><div id=list class=grid>${C.map(course).join("")}</div>`)}
function detail(i){let c=C[i];return shell(`<button onclick="go('courses')">← Courses</button><div class=card><span class=pill>${c[0]} • ${c[1]}</span><h1>${c[1]}</h1><div class=price>₹${c[2]}</div>${c[3]?`<div class=admin>✓ Course unlocked</div><h3>Course Content</h3>${["Introduction","Chapter 1","Chapter 2","Chapter 3","Practice Test"].map(x=>`<div class=card>▶ ${x}<small> Video + PDF + Test</small></div>`).join("")}`:`<p>Video lessons, notes and tests after purchase.</p><button class=btn onclick=buy()>Buy Now — ₹${c[2]}</button>`}<h3>💬 Comments</h3>${comments.map(x=>`<div class=comment><b>${x[0]}</b><div>${x[1]}</div></div>`).join("")}<form onsubmit=comment(event)><input id=ct required placeholder="Write a comment..." style="margin-bottom:8px"><button class=btn>Post Comment</button></form></div>`)}
function livePage(){return shell(`<h2>🔴 Live Classes</h2><div class=grid>${live.map((x,i)=>`<div class=card><span class=pill>${x[2]}</span><h3>${x[0]}</h3><p>${x[1]}</p><button class=btn onclick=liveRoom(${i})>${x[2]=='LIVE'?'Join Live':'Set Reminder'}</button></div>`).join("")}</div><div class=admin>Live video integration is ready for connection to a trusted streaming/video provider. Teacher controls should be secured on the server.</div>`)}
function liveRoom(i){let x=live[i];return shell(`<button onclick=go('live')>← Live</button><div class=card><span class=pill>🔴 LIVE NOW</span><h1>${x[0]}</h1><div class=video>🎥 LIVE VIDEO AREA<br><small>Connect secure live-stream provider here</small></div><h3>💬 Live Chat</h3>${comments.map(x=>`<div class=comment><b>${x[0]}</b><div>${x[1]}</div></div>`).join("")}<form onsubmit=comment(event)><input id=ct required placeholder="Ask your teacher..." style="margin-bottom:8px"><button class=btn>Send</button></form></div>`)}
function recorded(){return shell(`<h2>🎬 Recorded Classes</h2><div class=grid>${rec.map((x,i)=>`<div class=card><span class=pill>${x[1]}</span><h3>${x[0]}</h3><p>${x[2]}</p><button class=btn onclick=video(${i})>Watch</button></div>`).join("")}</div>`)}
function video(i){let x=rec[i];return shell(`<button onclick=go('recorded')>← Recorded</button><div class=card><h1>${x[0]}</h1><div class=video>▶️ SECURE VIDEO PLAYER AREA<br><small>Add protected video URL on server</small></div><h3>💬 Comments</h3>${comments.map(x=>`<div class=comment><b>${x[0]}</b><div>${x[1]}</div></div>`).join("")}<form onsubmit=comment(event)><input id=ct required placeholder="Write a comment..." style="margin-bottom:8px"><button class=btn>Post Comment</button></form></div>`)}
function profile(){return shell(`<div class=card><h2>Student Profile</h2><p>THE LEARNING ACADEMY</p><p>Purchased courses: ${C.filter(x=>x[3]).length}</p><button class=btn onclick=go('admin')>Admin Dashboard</button></div>`)}
function admin(){return shell(`<h2>⚙️ Admin Dashboard</h2><div class=grid><div class=card><b>${C.length}</b><br>Courses</div><div class=card><b>${live.length}</b><br>Live Classes</div><div class=card><b>${rec.length}</b><br>Recorded Classes</div></div><h3>Admin Controls</h3><div class=grid>${["Add/Edit/Delete Courses","Set Subject & Full-Course Prices","Schedule Live Classes","Add Recorded Videos","Upload Notes/PDFs","Create Tests & Quizzes","Moderate Comments","Manage Orders & Payments","Send Notifications","Student Progress"].map(x=>`<div class=card>✓ ${x}</div>`).join("")}</div><div class=admin>Before live launch: add secure authentication/database, server-side payment verification, protected video/PDF access and real live-stream infrastructure.</div>`)}
function go(p){page=p;render();scrollTo(0,0)}function openC(i){sel=i;go('detail')}function buy(){alert("Demo only. Real payment gateway must be connected with server-side verification before accepting money.")}function comment(e){e.preventDefault();let v=ct.value.trim();if(v){comments.push(["Student",v]);render()}}function filter(q){q=q.toLowerCase();list.innerHTML=C.filter(c=>(c[0]+" "+c[1]).toLowerCase().includes(q)).map(course).join("")}
function render(){app.innerHTML=page=="home"?home():page=="courses"?courses():page=="detail"?detail(sel):page=="live"?livePage():page=="liveRoom"?liveRoom(0):page=="recorded"?recorded():page=="video"?video(sel):page=="profile"?profile():admin()}render();